import { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | cvm",
  },
  description: "Generated by me bitch period",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="bg-pink-300 min-h-screen flex flex-col">
        <div className="flex-grow p-4">
          <header className="bg-red-800 p-4">
            <p>header</p>
          </header>
          {children}
        </div>
        <div className="p-4">
          <footer className="p-4 bg-blue-800">
            <p>footer</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
