import { Metadata } from "next";
import "./global.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | cvm",
  },
  description: "Generated by me.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="bg-pink-300 min-h-screen flex">
        <SidebarProvider>
          <AppSidebar />
          <div className="flex flex-col flex-grow">
            <header className="bg-blue-400 rounded-md p-4 m-4 mb-0">
              <SidebarTrigger />
            </header>
            <main className="flex-grow p-4 m-4 rounded-md bg-white">
              <ErrorWrapper>{children}</ErrorWrapper>
            </main>
            <footer className="bg-red-400 p-4 m-4 mt-0 rounded-md ">
              <p>footer</p>
            </footer>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
